version: "3.8"

services:
  rasa:
    build: .
    ports:
      - "5005:5005"
    volumes:
      - .:/app
    environment:
      - RASA_API_URL=http://rasa:5005
      - RASA_ACTIONS_URL=http://action-server:5055
    command:
      - run
      - --enable-api
      - --cors
      - "*"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5005/status"]
      interval: 30s
      timeout: 10s
      retries: 3

  action-server:
    build: ./actions
    ports:
      - "5055:5055"
    volumes:
      - ./actions:/app/actions
    environment:
      - RASA_ACTIONS_URL=http://action-server:5055
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5055/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    build: ./api
    ports:
      - "8034:8034"
    environment:
      - RASA_API_URL=http://rasa:5005
    depends_on:
      rasa:
        condition: service_healthy
      action-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8034/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3