services:
  - type: web
    name: event-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: RASA_API_URL
        value: https://rasa-server.onrender.com
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
    autoDeploy: true 