services:
  - type: web
    name: rasa-server
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: RASA_API_URL
        value: http://rasa-server:5005
    
  - type: web
    name: action-server
    env: docker
    dockerfilePath: ./actions/Dockerfile
    plan: free

  - type: web
    name: fastapi-server
    env: docker
    dockerfilePath: ./api/Dockerfile
    plan: free
    envVars:
      - key: RASA_API_URL
    plan: standard
    healthCheckPath: /health
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: rasa run actions
    envVars:
      - key: RASA_ACTIONS_URL
        value: https://action-server.onrender.com
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.7 