services:
  - type: web
    name: rasa-server
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: RASA_API_URL
        value: http://rasa-server:5005
      - key: RASA_ACTIONS_URL
        value: https://action-server.onrender.com
      - key: PORT
        value: 5005

  - type: web
    name: action-server
    env: docker
    dockerfilePath: ./actions/Dockerfile
    plan: free
    envVars:
      - key: RASA_ACTIONS_URL
        value: https://action-server.onrender.com
      - key: PORT
        value: 5055

  - type: web
    name: fastapi-server
    env: docker
    dockerfilePath: ./api/Dockerfile
    plan: free
    envVars:
      - key: RASA_API_URL
        value: https://rasa-server.onrender.com
      - key: PORT
        value: 8034 