services:
  - type: web
    name: rasa-server
    env: docker
    dockerfilePath: ./Dockerfile
    plan: standard
    healthCheckPath: /status
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: RASA_API_URL
        value: https://rasa-server.onrender.com
      - key: ACTION_SERVER_URL
        value: https://action-server.onrender.com
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.8

  - type: web
    name: action-server
    env: docker
    dockerfilePath: ./actions/Dockerfile
    plan: standard
    healthCheckPath: /health
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: rasa run actions
    envVars:
      - key: RASA_ACTIONS_URL
        value: https://action-server.onrender.com
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.8 